var AppConstant={
    LOGIN_USER : "LOGIN_USER",
    LOGIN_USER_SUCCESS : "LOGIN_USER_SUCCESS",
    USER_ONLINE: "USER_ONLINE",
    FRIEND_LIST_UPDATED: "FRIEND_LIST_UPDATED",
    CHANGE_FRIEND: "CHANGE_FRIEND",
    CHANGE_FRIEND_SUCCESS: "CHANGE_FRIEND_SUCCESS",
    NEW_MESSAGE: "NEW_MESSAGE",
    SYNC_MESSAGE: "SYNC_MESSAGE",
    OFFLINE_MODE: "OFFLINE_MODE"

};

module.exports=AppConstant